### PR TITLE
Fix tox factor name to actually run tests.

### PR DESCRIPTION
**Pull request by zsiciarz**
While attempting to start work on #24, I've noticed that all tox envs are green but... tox doesn't actually run the tests. This PR fixes factor name in tox.ini so that the proper commands are executed.

### CODE REVIEW

**Comment by zsiciarz** [comment]
Travis build failed due to hard dependency on RabbitMQ which doesn't seem to be set up in .travis.yml. But let me tackle that later.

**Comment by zsiciarz** [comment]
Travis build failed due to inaccessible RabbitMQ management API.

**Comment by mattbennett** [comment]
😳 

Thanks for fixing this! Looks like we're now being bitten by https://travis-ci.community/t/is-rabbitmq-service-down/4362/2

Adding `dist: trusty` to the travis conf should fix it.

**Comment by zsiciarz** [comment]
Thanks Matt, I got the tests to run. Well, not on Python 3.4 as PyYAML doesn't support that version anymore. In other cases the tests run, but I'd argue that getting them to pass should happen in another issue/PR.

**Comment by zsiciarz** [comment]
Closing thiis as Travis CI isn't relevant anymore. Will try to port CI for nameko-sentry to Github Actions in another PR.

**Pull request closed without merging**
